### ISSUE TITLE
PHP_CodeSniffer version 1.5.0RC2 (beta)

### ISSUE THREAD

**Issue by psychicLocust** [escapestudios/Symfony2-coding-standard#9]
Getting the following errors when trying to use the Symfony Coding Standard with phpcs 1.5.0RC2(beta)

```bash
PHP Strict Standards:  Declaration of Symfony2_Sniffs_Commenting_FunctionCommentSniff::processReturn() should be compatible with PEAR_Sniffs_Commenting_FunctionCommentSniff::processReturn($commentStart, $commentEnd) in /usr/share/php/PHP/CodeSniffer/Standards/Symfony2/Sniffs/Commenting/FunctionCommentSniff.php on line 35
PHP Strict Standards:  Declaration of Symfony2_Sniffs_Commenting_FunctionCommentSniff::processParams() should be compatible with PEAR_Sniffs_Commenting_FunctionCommentSniff::processParams($commentStart) in /usr/share/php/PHP/CodeSniffer/Standards/Symfony2/Sniffs/Commenting/FunctionCommentSniff.php on line 35
PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_Tokenizers_Comment not found' in /usr/share/php/PHP/CodeSniffer/Standards/Symfony2/Sniffs/Commenting/ClassCommentSniff.php:19
Stack trace:
#0 /usr/share/php/PHP/CodeSniffer.php(939): include_once()
#1 /usr/share/php/PHP/CodeSniffer.php(422): PHP_CodeSniffer->registerSniffs(Array, Array)
#2 /usr/share/php/PHP/CodeSniffer/CLI.php(614): PHP_CodeSniffer->process(Array, Array, Array, false)
#3 /usr/bin/phpcs(37): PHP_CodeSniffer_CLI->process()
#4 {main}
  thrown in /usr/share/php/PHP/CodeSniffer/Standards/Symfony2/Sniffs/Commenting/ClassCommentSniff.php on line 19
```

**Comment by djoos** [comment]
Hi @psychicLocust,

thanks for getting in touch!

In order to run these Symfony2 coding standard with PHP_CodeSniffer 1.x, you need to either grab the 1.x-branch of the repository or alternatively grab release 1.0.0. Or just upgrade PHP_CodeSniffer to 2.x.

Don't use the master (2.x) with PHP_CodeSniffer 1.x as that is bound to give you issues...

Hope this helps!

Kind regards,
David
